// Ported verbatim from ProxLab public/js/modules/ai.js — LLM launch engine data.
// Per-engine arg schemas (basic + advanced) for rendering the settings form + building commands.
/* eslint-disable */
// @ts-nocheck

export const MODEL_IDENTIFIER_FLAG_BY_PROVIDER = {
    'llama-server':     '--alias',
    'vllm':             '--served-model-name',
    '1cat-vllm':        '--served-model-name',
    'sglang':           '--served-model-name',
    'aphrodite':        '--served-model-name',
    'lmdeploy':         '--model-name',
  };

export const SLOT_SETTING_KEY_BY_PROVIDER = {
    'llama-server':     'parallel',
    'koboldcpp':        'multiuser',
    'vllm':             'maxNumSeqs',
    '1cat-vllm':        'maxNumSeqs',
  };


export const LAUNCH_TEMPLATES = {
    koboldcpp: {
      command: '/opt/koboldcpp/koboldcpp',
      useKcpps: true,
      args: {
        model:       { type: 'path', required: true },
        port:        { type: 'number', default: '' },
        contextSize: { kcpps: 'contextsize',    type: 'number', default: 8192 },
        gpuLayers:   { kcpps: 'gpulayers',      type: 'number', default: 999 },
        tensorSplit: { kcpps: 'tensor_split',   type: 'string', default: '' },
        quantKv:     { kcpps: 'quantkv',        type: 'select', default: '0',
                       options: ['0', '1', '2'], labels: { '0': 'FP16 (default)', '1': 'Q8', '2': 'Q4' } },
        flashAttn:   { kcpps: 'flashattention', type: 'flag',   default: true },
        contextShift:{ kcpps: 'contextshift',   type: 'flag',   default: true },
        debugMode:   { kcpps: 'debugmode',      type: 'number', default: 0 },
        threads:     { kcpps: 'threads',        type: 'number', default: 8 },
      },
      advancedArgs: {
        batchSize:        { kcpps: 'batchsize',               type: 'number', default: 512 },
        multiuser:        { kcpps: 'multiuser',               type: 'number', default: 1 },
        defaultGenAmt:    { kcpps: 'defaultgenamt',           type: 'number', default: 896 },
        maxRequestSize:   { kcpps: 'maxrequestsize',          type: 'number', default: 32 },
        chatAdapter:      { kcpps: 'chatcompletionsadapter',  type: 'select', default: 'AutoGuess',
                            options: [
                              'AutoGuess', '',
                              'ChatML', 'ChatML-NoThink',
                              'Llama-3', 'Llama-4', 'Llama-2-Chat',
                              'Mistral-Tekken', 'Mistral-NonTekken',
                              'DeepSeek', 'Gemma', 'Phi-3',
                              'Command-R', 'Granite-4', 'Jamba',
                              'GLM-4', 'GLM-4-NoThink', 'GLM-4.7-NoThink',
                              'Seed-OSS', 'Seed-OSS-NoThink',
                              'MiniMax', 'OpenAI-Harmony',
                              'Alpaca', 'Vicuna', 'Metharme', 'RWKV-World',
                            ],
                            labels: { '': 'None', 'ChatML-NoThink': 'ChatML NoThink (Qwen3/3.5)' },
                            label: 'Chat Adapter',
                            tooltip: 'Pre-made prompt format. Ignored (and auto-cleared) when Jinja Templates is enabled — the model\'s own template from the GGUF takes precedence' },
        jinja:            { kcpps: 'jinja',                   type: 'flag',   default: false,
                            label: 'Jinja Templates',
                            tooltip: 'Use the model\'s built-in Jinja chat template from the GGUF metadata. Required for correct formatting on Qwen3/3.5, Gemma 4, Llama 3, etc. When enabled, Chat Adapter is ignored' },
        jinjaKwargs:      { kcpps: 'jinja_kwargs',            type: 'select', default: '',
                            options: [
                              '',
                              '{"enable_thinking": false}',
                              '{"enable_thinking": true}',
                              '{"preserve_thinking": true}',
                              '{"enable_thinking": false, "preserve_thinking": true}',
                            ],
                            labels: {
                              '': 'template default',
                              '{"enable_thinking": false}': 'disable thinking prefix (Qwen3.5, Qwen3)',
                              '{"enable_thinking": true}': 'force thinking prefix (Gemma 4 Thinking)',
                              '{"preserve_thinking": true}': 'preserve historical thinking (Qwen3.6)',
                              '{"enable_thinking": false, "preserve_thinking": true}': 'Qwen3.6 instruct + preserve history',
                            },
                            label: 'Jinja Kwargs',
                            tooltip: 'JSON kwargs passed to the Jinja chat template — THIS is the primary lever for controlling whether the model thinks. Only applied when Jinja Templates is enabled.\n• Qwen3.5 / Qwen3: enable_thinking defaults to true; pick "disable thinking prefix" for the non-thinking variant\n• Qwen3.6: pick "preserve historical thinking" for agent loops where earlier think blocks add context (saves tokens, improves consistency); default keeps only the latest block\n• Gemma 4 Thinking: pick "force thinking prefix" — injects the <|think|> token at the start of the system prompt (Gemma 4\'s documented thinking trigger)' },
        useMmap:          { kcpps: 'usemmap',                 type: 'flag',   default: false },
        useMlock:         { kcpps: 'usemlock',                type: 'flag',   default: false },
        noFastForward:    { kcpps: 'nofastforward',           type: 'flag',   default: false },
        useSwa:           { kcpps: 'useswa',                  type: 'flag',   default: false },
        smartContext:     { kcpps: 'smartcontext',             type: 'flag',   default: false },
        smartCache:      { kcpps: 'smartcache',              type: 'number', default: 0 },
        lowVram:          { kcpps: 'lowvram',                 type: 'flag',   default: false },
        moeExperts:       { kcpps: 'moeexperts',              type: 'number', default: -1 },
        moeCpu:           { kcpps: 'moecpu',                  type: 'number', default: 0 },
        admin:            { kcpps: 'admin',                   type: 'flag',   default: true },
        adminPassword:    { kcpps: 'adminpassword',           type: 'string', default: '' },
        pipelineParallel: { kcpps: 'pipelineparallel',        type: 'flag',   default: false },
        embeddings:       { kcpps: 'embeddingsmodel',        type: 'flag',   default: false,
                            label: 'Enable Embeddings',
                            tooltip: 'Serve /v1/embeddings using the loaded model' },
        embeddingsMaxCtx: { kcpps: 'embeddingsmaxctx',       type: 'number', default: 0,
                            label: 'Embeddings Max Context',
                            tooltip: 'Max context for embeddings (0 = same as main context)' },
        embeddingsGpu:    { kcpps: 'embeddingsgpu',          type: 'flag',   default: false,
                            label: 'Embeddings on GPU',
                            tooltip: 'Run embeddings model on GPU' },
      },
    },
    ollama: {
      command: 'ollama run',
      args: {
        model:   { flag: '', type: 'path', required: true, positional: true },
        verbose: { flag: '--verbose', type: 'flag', default: true },
      },
    },
    vllm: {
      command: '/opt/conda/envs/vllm/bin/vllm serve',
      args: {
        model:          { flag: '',                         type: 'path',   required: true, positional: true },
        port:           { flag: '--port',                   type: 'number', default: '' },
        contextSize:    { flag: '--max-model-len',          type: 'number', default: 8192 },
        tensorParallel: { flag: '--tensor-parallel-size',   type: 'number', default: 1 },
        dtype:          { flag: '--dtype',                  type: 'select', default: 'float16', options: ['float16', 'bfloat16', 'auto'] },
        gpuMemUtil:     { flag: '--gpu-memory-utilization', type: 'number', default: 0.90, step: 0.05, min: 0.5, max: 0.99 },
        trustRemote:    { flag: '--trust-remote-code',      type: 'flag',   default: true },
        logRequests:    { flag: '--enable-log-requests',    type: 'flag',   default: true },
        logOutputs:     { flag: '--enable-log-outputs',     type: 'flag',   default: true },
        maxLogLen:      { flag: '--max-log-len',            type: 'number', default: 200 },
      },
    },
    sglang: {
      command: '/opt/conda/envs/sglang/bin/python -m sglang.launch_server',
      args: {
        model:          { flag: '--model-path',            type: 'path',   required: true },
        port:           { flag: '--port',                  type: 'number', default: '' },
        contextSize:    { flag: '--context-length',        type: 'number', default: 8192 },
        tensorParallel: { flag: '--tp',                    type: 'number', default: 1 },
        dtype:          { flag: '--dtype',                 type: 'select', default: 'float16', options: ['float16', 'bfloat16', 'auto'] },
        memFraction:    { flag: '--mem-fraction-static',   type: 'number', default: 0.88, step: 0.05, min: 0.5, max: 0.99 },
        trustRemote:    { flag: '--trust-remote-code',     type: 'flag',   default: true },
        logRequests:    { flag: '--log-requests',           type: 'flag',   default: true },
      },
    },
    lmdeploy: {
      command: '/opt/conda/envs/lmdeploy/bin/lmdeploy serve api_server',
      args: {
        model:          { flag: '',                        type: 'path',   required: true, positional: true },
        port:           { flag: '--server-port',           type: 'number', default: '' },
        contextSize:    { flag: '--session-len',           type: 'number', default: 8192 },
        tensorParallel: { flag: '--tp',                    type: 'number', default: 1 },
        cacheMaxEntry:  { flag: '--cache-max-entry-count', type: 'number', default: 0.8, step: 0.1, min: 0.1, max: 0.99 },
        logLevel:       { flag: '--log-level',             type: 'select', default: 'INFO', options: ['DEBUG', 'INFO', 'WARNING'] },
      },
    },
    tabbyapi: {
      command: '/opt/conda/envs/tabbyapi/bin/python /opt/tabbyapi/main.py',
      splitModelPath: true, // model path split into --model-dir (parent) + --model-name (leaf)
      args: {
        model:          { flag: '--model-dir',               type: 'path',   required: true },
        modelName:      { flag: '--model-name',              type: 'derived' },
        port:           { flag: '--port',                    type: 'number', default: '' },
        contextSize:    { flag: '--max-seq-len',             type: 'number', default: 8192 },
        tensorParallel: { flag: '--tensor-parallel',         type: 'select', default: '', options: ['true', 'false'] },
        tpBackend:      { flag: '--tensor-parallel-backend', type: 'select', default: 'native', options: ['native', 'nccl'] },
        gpuSplit:       { flag: '--gpu-split',               type: 'string', default: '' },
        logPrompt:      { flag: '--log-prompt',              type: 'select', default: 'true', options: ['true', 'false'] },
        logGenParams:   { flag: '--log-generation-params',   type: 'select', default: 'true', options: ['true', 'false'] },
        logRequests:    { flag: '--log-requests',            type: 'select', default: 'true', options: ['true', 'false'] },
        disableAuth:    { flag: '--disable-auth',            type: 'select', default: 'true', options: ['true', 'false'] },
        host:           { flag: '--host',                    type: 'string', default: '0.0.0.0' },
      },
    },
    aphrodite: {
      command: '/opt/conda/envs/aphrodite/bin/aphrodite run',
      args: {
        model:          { flag: '',                         type: 'path',   required: true, positional: true },
        port:           { flag: '--port',                   type: 'number', default: '' },
        contextSize:    { flag: '--max-model-len',          type: 'number', default: 8192 },
        tensorParallel: { flag: '--tensor-parallel-size',   type: 'number', default: 1 },
        dtype:          { flag: '--dtype',                  type: 'select', default: 'float16', options: ['float16', 'bfloat16', 'auto'] },
        gpuMemUtil:     { flag: '--gpu-memory-utilization', type: 'number', default: 0.90, step: 0.05, min: 0.5, max: 0.99 },
        trustRemote:    { flag: '--trust-remote-code',      type: 'flag',   default: true },
        logRequests:    { flag: '--enable-log-requests',    type: 'flag',   default: true },
        logOutputs:     { flag: '--enable-log-outputs',     type: 'flag',   default: true },
      },
    },
    'llama-server': {
      command: '/opt/llama-server/run.sh',
      supportsMmproj: true,
      args: {
        model:        { flag: '--model',         type: 'path',   required: true },
        port:         { flag: '--port',          type: 'number', default: '',
                          tooltip: 'HTTP port the server listens on' },
        host:         { flag: '--host',          type: 'string', default: '0.0.0.0',
                          tooltip: 'Bind address. 0.0.0.0 accepts from anywhere, 127.0.0.1 localhost only' },
        contextSize:  { flag: '--ctx-size',      type: 'number', default: 8192,
                          label: 'Context Size',
                          tooltip: 'Total KV-cache context length in tokens. Higher = more memory usage. 0 = use model\'s trained value' },
        gpuLayers:    { flag: '--gpu-layers',    type: 'string', default: '999',
                          label: 'GPU Layers',
                          tooltip: 'Number of model layers to offload to GPU. 999 = offload everything that fits, 0 = CPU-only' },
        tensorSplit:  { flag: '--tensor-split',  type: 'string', default: '',
                          label: 'Tensor Split',
                          tooltip: 'Comma-separated per-GPU proportions (e.g. "1,1,1,1" for 4 equal GPUs, "3,1" for 75/25 split). Empty = auto-distribute' },
        flashAttn:    { flag: '--flash-attn',    type: 'select', default: 'auto',
                          options: ['auto', 'on', 'off'],
                          label: 'Flash Attention',
                          tooltip: 'Enables fused attention kernels — faster and much less VRAM for long contexts. Leave on auto unless you hit a kernel bug' },
        parallel:     { flag: '--parallel',      type: 'number', default: 1,
                          tooltip: 'Number of concurrent request slots. Roleplay = 1; batch serving = higher. Each slot splits the context budget' },
        jinja:        { flag: '--jinja',         type: 'flag',   default: true,
                          label: 'Jinja Templates',
                          tooltip: 'Use the model\'s built-in Jinja chat template from its GGUF metadata. Required for correct formatting on Qwen3, Llama3, etc.' },
        threads:      { flag: '--threads',       type: 'number', default: -1,
                          tooltip: 'CPU threads for work not on the GPU. -1 = auto-detect physical cores' },
      },
      advancedArgs: {
        mmproj:          { type: 'string', default: '',
                            label: 'mmproj (vision projector)',
                            tooltip: 'Multimodal projector .gguf that enables image/vision input. Auto-filled from the model folder’s mmproj/ subdir when the selected model ships one — clear it to run text-only, or paste a different projector path. Emitted as --mmproj (no flag here; handled by the command builder so the path is cache-translated).' },
        batchSize:       { flag: '--batch-size',        type: 'number', default: 2048,
                            label: 'Batch Size',
                            tooltip: 'Logical batch size for prompt processing. Larger = faster ingest, more VRAM' },
        ubatchSize:      { flag: '--ubatch-size',       type: 'number', default: 512,
                            label: 'Micro-Batch Size',
                            tooltip: 'Physical batch chunk per forward pass. Must be ≤ batch size' },
        threadsBatch:    { flag: '--threads-batch',     type: 'number', default: -1,
                            label: 'Batch Threads',
                            tooltip: 'Threads used during prompt/batch processing. -1 = match --threads' },
        cachePrompt:     { flag: '--cache-prompt',      type: 'flag',   default: true,
                            label: 'Cache Prompt',
                            tooltip: 'Reuse prompt KV across requests — big speedup when the prefix matches' },
        cacheReuse:      { flag: '--cache-reuse',       type: 'number', default: 0, skipIfZero: true,
                            label: 'Cache Reuse',
                            tooltip: 'Minimum chunk size that can be reused via KV shifting (0 = disabled). Enables partial cache reuse when prompts diverge in the middle. Try 256 for agentic workloads.' },
        cacheRam:        { flag: '--cache-ram',         type: 'number', default: 8192,
                            label: 'Prompt Cache RAM (MiB)',
                            tooltip: 'Maximum prompt-cache RAM in MiB (default 8192 = 8 GiB). The cache stores tokenized+KV state from previous prompts for prefix-match reuse. Raise if cross-prompt similarity searches return poor matches due to LRU eviction. -1 = unlimited.' },
        ctxCheckpoints:  { flag: '--ctx-checkpoints',   type: 'number', default: 0, skipIfZero: true,
                            label: 'Context Checkpoints/Slot',
                            tooltip: 'Max number of mid-prompt KV checkpoints per slot (0 = use llama.cpp default). More checkpoints = finer-grained partial cache reuse on diverging prompts.' },
        checkpointEveryNTokens: { flag: '--checkpoint-min-step',
                            type: 'number', default: 0, skipIfZero: true,
                            label: 'Checkpoint Every N Tokens',
                            tooltip: 'During prefill, create a KV checkpoint every N tokens. Lets llama.cpp resume from mid-prompt on prefix divergence. -1 to disable.' },
        slotPromptSimilarity: { flag: '--slot-prompt-similarity', type: 'number', default: 0.5,
                            label: 'Slot Prompt Similarity Threshold',
                            tooltip: 'Minimum prefix-match fraction (0.0-1.0) for a new prompt to attach to an existing slot rather than evicting it. Lower = more aggressive reuse, risk of incorrect attachment. Default 0.5.' },
        cacheTypeK:      { flag: '--cache-type-k',      type: 'select', default: 'f16',
                            options: ['f32', 'f16', 'bf16', 'q8_0', 'q4_0', 'q4_1', 'iq4_nl', 'q5_0', 'q5_1'],
                            label: 'KV Cache K Quant',
                            tooltip: 'Quantization of the K (key) KV cache. q8_0 halves VRAM with tiny quality loss; q4_0 halves again but can degrade' },
        cacheTypeV:      { flag: '--cache-type-v',      type: 'select', default: 'f16',
                            options: ['f32', 'f16', 'bf16', 'q8_0', 'q4_0', 'q4_1', 'iq4_nl', 'q5_0', 'q5_1'],
                            label: 'KV Cache V Quant',
                            tooltip: 'Quantization of the V (value) KV cache. Pair with K quant. Some models require flash-attn for V quants' },
        swaFull:         { flag: '--swa-full',          type: 'flag',   default: false,
                            label: 'SWA Full',
                            tooltip: 'Use full-size sliding-window-attention cache. Enables prompt reuse on SWA models at the cost of more VRAM' },
        contextShift:    { flag: '--context-shift',     type: 'flag',   default: false,
                            label: 'Context Shift',
                            tooltip: 'Auto-trim oldest tokens when context fills up. Without this, generation stops at ctx limit' },
        splitMode:       { flag: '--split-mode',        type: 'select', default: 'layer',
                            options: ['none', 'layer', 'row', 'tensor'],
                            label: 'Split Mode',
                            tooltip: 'How to split across GPUs. "layer" (default) = pipeline, one layer-range per GPU (best for MoE — continuous-batches concurrent slots cheaply). "row"/"tensor" = split each layer across GPUs in parallel (tensor parallelism) — best for DENSE models (e.g. 27B), wins on both latency and concurrent throughput. NOTE for "tensor": set Param Fit = off (below) quantized KV cache (q8_0 etc.) is supported with tensor split on current builds; the bundle is built with NCCL so the cross-GPU AllReduce runs over NVLink.' },
        fit:             { flag: '--fit',               type: 'select', default: 'on',
                            options: ['on', 'off'],
                            label: 'Param Fit (off for tensor)',
                            tooltip: 'Auto-fit unset args to free VRAM (llama.cpp default = on; no-op when --gpu-layers and --ctx-size are set explicitly, as they always are here). MUST be set to "off" when Split Mode = tensor — the auto-fitter is not implemented for tensor-parallel and aborts the launch otherwise. Both the mainline and ik_llama MTP binaries accept this flag.' },
        mainGpu:         { flag: '--main-gpu',          type: 'number', default: 0,
                            label: 'Main GPU',
                            tooltip: 'GPU index that holds the small tensors not split. Usually 0' },
        cpuMoe:          { flag: '--cpu-moe',           type: 'flag',   default: false,
                            label: 'All MoE Experts on CPU',
                            tooltip: 'Offload every MoE expert tensor to CPU/RAM. Biggest VRAM savings for MoE models (Qwen3.5-MoE, Mixtral) but slower generation' },
        nCpuMoe:         { flag: '--n-cpu-moe',         type: 'number', default: 0, skipIfZero: true,
                            label: 'MoE Experts on CPU (first N)',
                            tooltip: 'Offload MoE experts for first N layers only. Tune until the model fits. Start 10-20, increase if OOM' },
        mlock:           { flag: '--mlock',             type: 'flag',   default: false,
                            label: 'mlock',
                            tooltip: 'Lock model weights in RAM so the OS won\'t swap them out. Needs sufficient RAM' },
        noMmap:          { flag: '--no-mmap',           type: 'flag',   default: false,
                            label: 'Disable mmap',
                            tooltip: 'Load the whole model into RAM instead of memory-mapping. Slower startup, avoids page-faulting during inference' },
        numa:            { flag: '--numa',              type: 'select', default: '',
                            options: ['', 'distribute', 'isolate', 'numactl'],
                            labels: { '': 'off' },
                            label: 'NUMA Policy',
                            tooltip: 'Multi-socket CPU policy. "distribute" = spread across nodes, "isolate" = pin to one node, "numactl" = use system numactl config' },
        overrideTensor:  { flag: '--override-tensor',  type: 'multi',  default: '',
                            label: 'Override-Tensor Rules (-ot)',
                            tooltip: 'One "regex=BUFFER" rule per line (device = CUDA0-7 or CPU). Pins matching tensors to a device; first match wins, so put the catch-all rule last. Used to spread MoE expert layers evenly across all GPUs (what --cpu-moe / --n-cpu-moe cannot do). Emitted as repeated --override-tensor flags.' },
        numaInterleave:  { flag: '--numactl-interleave', type: 'flag',  default: false,
                            label: 'NUMA Interleave (numactl)',
                            tooltip: 'Wrap the server in `numactl --interleave=all` so CPU-resident weights are round-robin placed across all NUMA nodes. Essential on dual-socket hosts when CPU experts exceed a single node RAM (prevents one memory controller overflowing / bottlenecking). Handled by run.sh; harmless on single-socket nodes.' },
        ropeScaling:     { flag: '--rope-scaling',      type: 'select', default: '',
                            options: ['', 'none', 'linear', 'yarn'],
                            labels: { '': 'model default' },
                            label: 'RoPE Scaling',
                            tooltip: 'Position-embedding extrapolation method for contexts beyond training length. "yarn" is preferred for Qwen/Mistral/Llama long-ctx' },
        ropeScale:       { flag: '--rope-scale',        type: 'number', default: 0, step: 0.5, skipIfZero: true,
                            label: 'RoPE Scale',
                            tooltip: '0 = disabled, else expand ctx by factor N (e.g. 2.0 doubles the effective ctx)' },
        ropeFreqBase:    { flag: '--rope-freq-base',    type: 'number', default: 0, skipIfZero: true,
                            label: 'RoPE Freq Base',
                            tooltip: 'Override RoPE theta. 0 = use model metadata. Common overrides: 1e6 or 1e7 for extended ctx' },
        yarnOrigCtx:     { flag: '--yarn-orig-ctx',     type: 'number', default: 0, skipIfZero: true,
                            label: 'YaRN Original Ctx',
                            tooltip: 'Original training context length, used by YaRN scaling math. 0 = read from model metadata' },
        reasoning:       { flag: '--reasoning',         type: 'select', default: 'auto',
                            options: ['auto', 'on', 'off'],
                            label: 'Reasoning Mode',
                            tooltip: 'Mostly redundant with Template Kwargs below — leave at "auto" in almost all cases.\nThis is a llama.cpp-side post-processing hint, NOT what actually turns thinking on or off in the model. The model\'s thinking is controlled by its chat template (use Template Kwargs to set enable_thinking).\n"on" / "off" can fight with model-specific reasoning formats (notably Gemma 4\'s <|channel|>thought tags) and produce mangled output. Only override if you\'ve verified your model needs it.' },
        reasoningFormat: { flag: '--reasoning-format',  type: 'select', default: '',
                            options: ['', 'auto', 'none', 'deepseek', 'deepseek-legacy'],
                            labels: { '': 'binary default (omit flag)', 'auto': 'auto (legacy — same as binary default)' },
                            skipIfValue: ['auto'],
                            label: 'Reasoning Format',
                            tooltip: 'How llama.cpp surfaces the reasoning stream in the /v1/chat/completions response.\n• (binary default) or auto: omit the flag, let llama.cpp pick.\n• none: returns raw model output unchanged — REQUIRED for Gemma 4 (its <|channel|>thought\\n…<channel|> format isn\'t recognized by auto-detection and gets mangled into empty <think></think> tags)\n• deepseek: separates thinking into a reasoning_content field (DeepSeek-R1, Qwen3.5 thinking)\n• deepseek-legacy: older variant of the above' },
        reasoningBudget: { flag: '--reasoning-budget',  type: 'number', default: -1,
                            label: 'Reasoning Budget Tokens',
                            tooltip: 'Max tokens for the reasoning/thinking phase. -1 = unlimited, 0 = no reasoning, else hard cap' },
        reasoningPreserve:{ flag: '--reasoning-preserve', type: 'select', default: '',
                            options: ['', 'on', 'off'],
                            bareFlags: { on: '--reasoning-preserve', off: '--no-reasoning-preserve' },
                            labels: { '': 'model/template default (omit flag)', 'on': 'on \u2014 --reasoning-preserve', 'off': 'off \u2014 --no-reasoning-preserve' },
                            label: 'Preserve Reasoning',
                            tooltip: 'Keep the model\'s reasoning/thinking block in its context across turns instead of stripping it.\n\nThis REPLACES the now-deprecated  --chat-template-kwargs \'{\"preserve_thinking\": true}\'  kwarg (build b10075+ prints "chat template supports preserving reasoning, consider enabling it via --reasoning-preserve" if you use the old kwarg). Use the native flag now.\n\u2022 (default): omit the flag, let the model/chat-template decide.\n\u2022 on: --reasoning-preserve (Qwen3.x / thinking models that benefit from seeing their prior reasoning).\n\u2022 off: --no-reasoning-preserve (force strip).\nEnv equiv: LLAMA_ARG_REASONING_PRESERVE. Note: enable/disable thinking itself is still the chat template\'s enable_thinking kwarg or --reasoning on/off \u2014 this only controls whether the produced reasoning is preserved.' },
        chatTemplate:    { flag: '--chat-template',     type: 'select', default: '',
                            options: ['', 'chatml', 'llama2', 'llama3', 'llama4',
                                      'mistral-v3', 'mistral-v3-tekken', 'mistral-v7', 'mistral-v7-tekken',
                                      'gemma', 'phi3', 'phi4', 'deepseek', 'deepseek2', 'deepseek3',
                                      'command-r', 'granite', 'granite-4.0',
                                      'glmedge', 'gpt-oss', 'kimi-k2', 'zephyr'],
                            labels: { '': 'model metadata (default)' },
                            label: 'Chat Template',
                            tooltip: 'Force a specific built-in chat template. Leave empty to use the Jinja template from the GGUF (preferred), or set Chat Template File below to load a custom one' },
        chatTemplateFile: { flag: '--chat-template-file', type: 'select', default: '',
                            options: ['', '/opt/1cat-vllm/froggeric-qwen36-chat_template.jinja'],
                            labels: { '': 'none (GGUF-embedded template)',
                                      '/opt/1cat-vllm/froggeric-qwen36-chat_template.jinja': 'Froggeric Qwen3.6 (tool-call fix)' },
                            label: 'Chat Template File',
                            tooltip: 'Load a custom Jinja chat template from a file, overriding the GGUF-embedded one. Use the Froggeric Qwen 3.6 template for the tool-call formatting fix. Requires --jinja (on by default). Leave empty to use the GGUF metadata template.' },
        chatTemplateKwargs: { flag: '--chat-template-kwargs', type: 'select', default: '',
                            options: [
                              '',
                              `{"enable_thinking": false}`,
                              `{"enable_thinking": true}`,
                              `{"preserve_thinking": true}`,
                              `{"enable_thinking": false, "preserve_thinking": true}`,
                            ],
                            labels: {
                              '': 'template default',
                              [`{"enable_thinking": false}`]: 'disable thinking prefix (Qwen3.5, Qwen3)',
                              [`{"enable_thinking": true}`]: 'force thinking prefix (Gemma 4 Thinking)',
                              [`{"preserve_thinking": true}`]: 'preserve historical thinking (Qwen3.6)',
                              [`{"enable_thinking": false, "preserve_thinking": true}`]: 'Qwen3.6 instruct + preserve history',
                            },
                            label: 'Template Kwargs',
                            tooltip: 'JSON kwargs passed to the Jinja chat template — THIS is the primary lever for controlling whether the model thinks. Far more reliable than the Reasoning Mode dropdown above.\n• Qwen3.5 / Qwen3: enable_thinking defaults to true; pick "disable thinking prefix" for the non-thinking variant\n• Qwen3.6: pick "preserve historical thinking" for agent loops where earlier think blocks add context (saves tokens, improves consistency); default keeps only the latest block\n• Gemma 4 Thinking: pick "force thinking prefix" — this injects the <|think|> token at the start of the system prompt (Gemma 4\'s documented thinking trigger). Pair with Reasoning Format = none, since Gemma 4\'s <|channel|> format would otherwise be mangled by auto post-processing.\n\n\u26a0 preserve_thinking here is DEPRECATED on this mainline (b10075+) build \u2014 use the \"Preserve Reasoning\" dropdown (--reasoning-preserve) above instead; the old kwarg still works but logs a deprecation notice.' },
        samplers:        { flag: '--samplers',          type: 'string', default: '',
                            label: 'Samplers',
                            tooltip: 'Semicolon-separated sampler order, e.g. "penalties;dry;top_k;min_p;temperature". Empty = llama.cpp default chain' },
        temp:            { flag: '--temp',              type: 'number', default: 0.8, step: 0.05, min: 0,
                            label: 'Temperature',
                            tooltip: 'Randomness. 0 = greedy, 1.0+ = creative. Qwen3/3.5: 0.6 for thinking mode, 0.7 for non-thinking' },
        topK:             { flag: '--top-k',             type: 'number', default: 40,
                            label: 'Top K',
                            tooltip: 'Keep only the K most likely tokens. 0 = disabled. 20 = Qwen3/3.5 rec (both modes), 40 = Llama default' },
        topP:            { flag: '--top-p',             type: 'number', default: 0.95, step: 0.01, min: 0, max: 1,
                            label: 'Top P',
                            tooltip: 'Nucleus sampling — keep smallest token set whose cumulative prob ≥ P. Qwen3/3.5: 0.95 for thinking mode, 0.8 for non-thinking' },
        minP:            { flag: '--min-p',             type: 'number', default: 0.05, step: 0.01, min: 0, max: 1,
                            label: 'Min P',
                            tooltip: 'Drop tokens below this fraction of the top token\'s probability. Usually 0.02-0.1' },
        repeatPenalty:   { flag: '--repeat-penalty',    type: 'number', default: 1.0,  step: 0.01,
                            label: 'Repeat Penalty',
                            tooltip: 'Penalty for tokens that already appeared. 1.0 = off, >1 = discourage repetition. Prefer DRY over this' },
        presencePenalty: { flag: '--presence-penalty',  type: 'number', default: 0.0,  step: 0.1, skipIfZero: true,
                            label: 'Presence Penalty',
                            tooltip: 'Flat penalty once a token has appeared. 0 = off. Qwen3/3.5 recommends 1.5 to keep thinking/reply blocks from degenerating into repeated phrases' },
        frequencyPenalty: { flag: '--frequency-penalty', type: 'number', default: 0.0,  step: 0.1, skipIfZero: true,
                            label: 'Frequency Penalty',
                            tooltip: 'Scales with token frequency. 0 = off. Usually leave 0 — use presence-penalty or DRY instead for modern models' },
        dryMultiplier:   { flag: '--dry-multiplier',    type: 'number', default: 0.0,  step: 0.1, skipIfZero: true,
                            label: 'DRY Multiplier',
                            tooltip: 'DRY (Don\'t Repeat Yourself) sampler strength. 0 = off, 0.8 = typical. Suppresses verbatim phrase repetition' },
        mirostat:        { flag: '--mirostat',          type: 'select', default: '0',
                            options: ['0', '1', '2'],
                            labels: { '0': 'off', '1': 'Mirostat', '2': 'Mirostat 2.0' },
                            label: 'Mirostat',
                            tooltip: 'Perplexity-targeting sampler. Overrides top-k/top-p when active. Rarely beats min_p + DRY for modern models' },
        apiKey:          { flag: '--api-key',           type: 'string', default: '',
                            label: 'API Key',
                            tooltip: 'Require this Bearer token for API access. Empty = no auth' },
        apiPrefix:       { flag: '--api-prefix',        type: 'string', default: '',
                            label: 'API Prefix',
                            tooltip: 'Mount API under a path prefix, e.g. /llama (no trailing slash). Useful behind a reverse proxy' },
        slotSavePath:    { flag: '--slot-save-path',    type: 'string', default: '', hidden: true,
                            label: 'Slot Save Path',
                            tooltip: 'Managed automatically — hidden. Every llama.cpp / ik_llama.cpp launch is always assigned an Optane KV slot at /optane-sock0/kvcache/<model-file>-<content-fingerprint>, derived from the model file + ctx + cache dtypes so the same model+settings maps to one slot regardless of port/GPUs/alias. Any value here is ignored and replaced by the server.' },
        metrics:         { flag: '--metrics',           type: 'flag',   default: true,
                            label: 'Prometheus Metrics',
                            tooltip: 'Enable /metrics endpoint — ProxLab reads llamacpp:predicted_tokens_seconds from here for live TPS' },
        slots:           { flag: '--slots',             type: 'flag',   default: true,
                            label: 'Slots Endpoint',
                            tooltip: 'Enable /slots monitoring endpoint. Shows per-slot state, useful for debugging multi-client setups' },
        noWebui:         { flag: '--no-webui',          type: 'flag',   default: false,
                            label: 'Disable Built-in WebUI',
                            tooltip: 'Disable the built-in browser chat UI on the root path. API-only mode' },
        embedding:       { flag: '--embedding',         type: 'flag',   default: false,
                            label: 'Embedding Mode',
                            tooltip: 'Only expose /v1/embeddings — disables completion/chat. Use an embedding model, not a chat model' },
        rerank:          { flag: '--rerank',            type: 'flag',   default: false,
                            label: 'Rerank Mode',
                            tooltip: 'Expose /v1/rerank. Requires a reranker model like bge-reranker or Qwen3-Reranker' },
        ignoreEos:       { flag: '--ignore-eos',        type: 'flag',   default: false,
                            label: 'Ignore EOS',
                            tooltip: 'Continue generating past the model\'s end-of-sequence token. Almost always a bad idea in production' },
        verbose:         { flag: '--verbose',           type: 'flag',   default: false,
                            label: 'Verbose Logging',
                            tooltip: 'Extra-chatty server logs — useful when debugging prompt formatting or slot issues' },
        modelDraft:      { flag: '--model-draft',       type: 'string', default: '',
                            label: 'Draft Model Path',
                            tooltip: 'Path to a small same-family draft GGUF for draft-simple/eagle3/dflash speculation. For draft-mtp, leave this blank and use the MTP-variant target model (built-in head). 1.5-2x on compute-bound models.' },
        draftMax:        { flag: '--spec-draft-n-max',         type: 'number', default: 16,
                            label: 'Draft Tokens',
                            tooltip: 'Max draft tokens proposed per step (--spec-draft-n-max; = DFlash block size). Higher helps on fast GPUs but HURTS on slower ones — on V100s ~4-6 usually beats 16.' },
        draftPmin:       { flag: '--draft-p-min',       type: 'number', default: 0.75, step: 0.05,
                            label: 'Draft Min Prob',
                            tooltip: 'Minimum probability a draft token needs to be proposed. Higher = fewer but more confident drafts' },
        ngpuLayersDraft: { flag: '--gpu-layers-draft',  type: 'string', default: '',
                            label: 'Draft GPU Layers',
                            tooltip: 'GPU offload count for the draft model. Empty = all on GPU' },
        specType:        { flag: '--spec-type',         type: 'select', default: '',
                            options: ['', 'draft-mtp', 'draft-dflash', 'draft-eagle3', 'draft-simple', 'ngram-simple', 'ngram-map-k', 'ngram-map-k4v', 'ngram-mod', 'ngram-cache'],
                            labels: {
                              '': 'draft-model (if Draft Model Path set) / none',
                              'draft-mtp': 'draft-mtp — built-in MTP heads (Qwen3.6-MTP); no draft model',
                              'draft-dflash': 'draft-dflash — DFlash block-diffusion (needs Draft Model Path)',
                              'draft-eagle3': 'draft-eagle3 — EAGLE-3 (needs Draft Model Path)',
                              'draft-simple': 'draft-simple — plain draft model (needs Draft Model Path)',
                              'ngram-simple': 'ngram-simple — statistical n-gram (no draft model)',
                              'ngram-map-k': 'ngram-map-k',
                              'ngram-map-k4v': 'ngram-map-k4v',
                              'ngram-mod': 'ngram-mod',
                              'ngram-cache': 'ngram-cache — cached n-gram',
                            },
                            label: 'Speculative Type',
                            tooltip: 'Speculative decoding strategy (llama.cpp b10075+ naming: draft-* / ngram-*). draft-mtp uses the target GGUFs built-in MTP heads (no draft model). draft-dflash/eagle3/simple need a Draft Model Path. ngram-* are model-agnostic (no draft model). Tune Draft Tokens per step. NOTE: spec-decode HELPS compute-bound (all-on-GPU) models but HURTS transfer-bound ones (MoE experts offloaded to CPU RAM).' },
        draftMin:        { flag: '--spec-draft-n-min',   type: 'number', default: 0, skipIfZero: true,
                            label: 'Draft Min Tokens',
                            tooltip: 'Minimum draft tokens per speculation step (--spec-draft-n-min). 0 = llama.cpp default.' },
        draftDevice:     { flag: '--spec-draft-device',  type: 'string', default: '',
                            label: 'Draft Device (pin)',
                            tooltip: 'Pin the draft model to specific device(s) e.g. CUDA0 (comma-separated for several). Keeps the small draft off the tensor-split so it does not fragment the main compute graph. Empty = follow main placement.' },
        noDraftBackendSampling: { flag: '--no-spec-draft-backend-sampling', type: 'flag', default: false,
                            label: 'Draft: force CPU sampler',
                            tooltip: 'Disable GPU/backend draft sampling and use the CPU sampler for draft tokens. Try if you hit backend offload failed for seq_id warnings during speculative decode.' },
        imageMinTokens:  { flag: '--image-min-tokens',  type: 'number', default: 0, skipIfZero: true,
                            label: 'Image Min Tokens',
                            tooltip: 'Vision models: minimum tokens an image expands to (0 = model default)' },
        imageMaxTokens:  { flag: '--image-max-tokens',  type: 'number', default: 0, skipIfZero: true,
                            label: 'Image Max Tokens',
                            tooltip: 'Vision models: maximum tokens per image — hard cap on image detail (0 = model default)' },
      },
    },
  };

  // ─── vLLM (standard) ────────────────────────────────────────────────
  // vLLM's CLI has 100+ flags; this template exposes the ~50 most-used,
  // organized into args (always-visible) and advancedArgs (collapsed).
  // Model path is POSITIONAL (`vllm serve /path/to/model`), not a flag.
  LAUNCH_TEMPLATES['vllm'] = {
    command: '/opt/conda/envs/vllm/bin/vllm serve',
    args: {
      model:        { type: 'path',   positional: true, required: true,
                        label: 'Model Path',
                        tooltip: 'Local HuggingFace checkpoint dir or hub repo id. Positional first argument to `vllm serve`.' },
      port:         { flag: '--port', type: 'number', default: '',
                        tooltip: 'HTTP port the OpenAI-compatible server listens on' },
      host:         { flag: '--host', type: 'string', default: '0.0.0.0',
                        tooltip: 'Bind address. 0.0.0.0 = LAN-reachable, 127.0.0.1 = loopback only' },
      tensorParallelSize: { flag: '--tensor-parallel-size', type: 'number', default: 1,
                        label: 'Tensor Parallel',
                        tooltip: 'Number of GPUs to shard each layer across. Set to # of GPUs you have allocated. 1 = single-GPU.' },
      maxModelLen:  { flag: '--max-model-len', type: 'number', default: 8192,
                        label: 'Max Model Length',
                        tooltip: 'Maximum context length (input + output tokens). Caps the model\'s trained context; reducing trades less KV cache memory for less context.' },
      maxNumSeqs:   { flag: '--max-num-seqs', type: 'number', default: 256,
                        label: 'Max Concurrent Sequences (slots)',
                        tooltip: 'Maximum concurrent requests being decoded. Lower = less KV cache pressure per request. Roleplay 1-4; chatbot 32-128; batch serving 256+.' },
      maxNumBatchedTokens: { flag: '--max-num-batched-tokens', type: 'number', default: 0, skipIfZero: true,
                        label: 'Max Batched Tokens',
                        tooltip: 'Total tokens scheduled per forward pass (prefill + decode). 0 = auto. Raise for higher prefill throughput; lower if hitting OOM during long-prompt ingestion. Typical: 8192-32768.' },
      gpuMemoryUtilization: { flag: '--gpu-memory-utilization', type: 'number', default: 0.9, step: 0.05,
                        label: 'GPU Mem Util',
                        tooltip: 'Fraction of total GPU memory vLLM is allowed to allocate (0.0-1.0). Lower if other processes share the GPU.' },
      quantization: { flag: '--quantization', type: 'select', default: '',
                        options: ['', 'awq', 'gptq', 'fp8', 'bitsandbytes', 'aqlm', 'compressed-tensors', 'marlin', 'awq_marlin', 'gptq_marlin', 'fbgemm_fp8', 'gguf', 'experts_int8'],
                        labels: { '': 'auto-detect from checkpoint' },
                        label: 'Quantization',
                        tooltip: 'Force a specific quantization kernel. Usually leave empty so vLLM auto-detects from the checkpoint\'s config.json.' },
      dtype:        { flag: '--dtype', type: 'select', default: 'auto',
                        options: ['auto', 'half', 'float16', 'bfloat16', 'float', 'float32'],
                        label: 'Compute Dtype',
                        tooltip: 'Activation dtype. "auto" follows model config. "half" needed on Volta (no bf16). Ada+ should use bfloat16.' },
      kvCacheDtype: { flag: '--kv-cache-dtype', type: 'select', default: 'auto',
                        options: ['auto', 'fp8', 'fp8_e5m2', 'fp8_e4m3'],
                        label: 'KV Cache Dtype',
                        tooltip: 'Quantize KV cache to fit more context. fp8_e5m2 = wider range; fp8_e4m3 = higher precision near zero. ~2x context for minimal quality loss.' },
      enablePrefixCaching: { flag: '--enable-prefix-caching', type: 'flag', default: true,
                        label: 'Enable Prefix Caching',
                        tooltip: 'Reuse KV cache across requests sharing a prefix (system prompt, RAG context, agent loops). Big win for agentic. Almost always on.' },
      trustRemoteCode: { flag: '--trust-remote-code', type: 'flag', default: false,
                        label: 'Trust Remote Code',
                        tooltip: 'Allow the model to execute arbitrary Python from its hub repo. REQUIRED for many newer models (Qwen, DeepSeek). Off by default.' },
      servedModelName: { flag: '--served-model-name', type: 'string', default: '',
                        label: 'Served Model Name',
                        tooltip: 'The id reported via /v1/models. Defaults to the model path if blank. ProxLab\'s service card alias can also override this at runtime.' },
      chatTemplate: { flag: '--chat-template', type: 'string', default: '',
                        label: 'Chat Template Path',
                        tooltip: 'Path to a custom Jinja chat template file; overrides the model bundled chat_template. Use for fixed tool-call templates (e.g. froggeric Qwen 3.5/3.6: /opt/1cat-vllm/froggeric-qwen36-chat_template.jinja). Blank = model default.' },
    },
    advancedArgs: {
      // Distributed
      pipelineParallelSize: { flag: '--pipeline-parallel-size', type: 'number', default: 1,
                        label: 'Pipeline Parallel',
                        tooltip: 'Split model across pipeline stages. Use TP first; only reach for PP if model doesn\'t fit even with TP across all GPUs.' },
      dataParallelSize: { flag: '--data-parallel-size', type: 'number', default: 1,
                        label: 'Data Parallel',
                        tooltip: 'Run N independent model replicas. Multiplies throughput; needs N copies of model weights in VRAM.' },
      distributedExecutor: { flag: '--distributed-executor-backend', type: 'select', default: '',
                        options: ['', 'ray', 'mp', 'uni', 'external_launcher'],
                        labels: { '': 'auto (mp for single-node)' },
                        label: 'Distributed Backend',
                        tooltip: '"mp" = multiprocess (fast, single-node); "ray" = Ray cluster (multi-node); "uni" = single-process.' },
      enforceEager: { flag: '--enforce-eager', type: 'flag', default: false,
                        label: 'Enforce Eager (no CUDA graphs)',
                        tooltip: 'Disable CUDA graph capture. Use for debugging or models that don\'t play well with graph capture. Costs throughput.' },
      disableHybridKvCache: { flag: '--disable-hybrid-kv-cache-manager', type: 'flag', default: false,
                        label: 'Disable Hybrid KV Cache',
                        tooltip: 'Force the uniform (non-hybrid) KV cache manager. Fixes the engine-init crash "HybridKVCacheCoordinator requires at least two attention groups" on sliding-window/hybrid-attention models (e.g. Nemotron rerank) whose window collapses to a single group at small context. Harmless for non-hybrid models.' },
      // Load format / Tokenizer
      loadFormat:   { flag: '--load-format', type: 'select', default: 'auto',
                        options: ['auto', 'pt', 'safetensors', 'npcache', 'dummy', 'tensorizer', 'sharded_state', 'gguf', 'bitsandbytes', 'mistral', 'runai_streamer'],
                        label: 'Load Format',
                        tooltip: 'Checkpoint file format. "auto" picks based on what\'s in the model dir.' },
      tokenizer:    { flag: '--tokenizer', type: 'string', default: '',
                        label: 'Tokenizer Path/Name',
                        tooltip: 'Override the tokenizer (defaults to the model dir). Useful when the model dir has a broken tokenizer.' },
      tokenizerMode: { flag: '--tokenizer-mode', type: 'select', default: 'auto',
                        options: ['auto', 'slow', 'mistral', 'custom'],
                        label: 'Tokenizer Mode',
                        tooltip: '"auto" = fast tokenizer; "slow" forces Python tokenizer; "mistral" for Mistral-format.' },
      chatTemplateContentFormat: { flag: '--chat-template-content-format', type: 'select', default: 'auto',
                        options: ['auto', 'string', 'openai'],
                        label: 'Content Format',
                        tooltip: '"string" = legacy plain-text content; "openai" = structured content blocks.' },
      responseRole: { flag: '--response-role', type: 'string', default: 'assistant',
                        label: 'Response Role',
                        tooltip: 'Role name returned in completion responses. Almost always "assistant".' },
      // Caching / Scheduling
      blockSize:    { flag: '--block-size', type: 'select', default: '',
                        options: ['', '8', '16', '32', '64', '128'],
                        labels: { '': 'auto' },
                        label: 'KV Block Size',
                        tooltip: 'Tokens per KV cache block. 16 is the historical default; some kernels (FA3, AWQ) need 64. Larger = lower overhead, coarser eviction.' },
      numGpuBlocksOverride: { flag: '--num-gpu-blocks-override', type: 'number', default: 0, skipIfZero: true,
                        label: 'Override GPU Blocks',
                        tooltip: 'Manually set the number of KV cache blocks. Advanced: only when auto sizing fails.' },
      // --swap-space and --preemption-mode were REMOVED in vLLM's V1 engine (no CPU swap;
      // preemption is recompute-only). They are re-declared in the 1cat-vllm override below,
      // which is an older fork that still accepts --swap-space.
      cpuOffloadGb: { flag: '--cpu-offload-gb', type: 'number', default: 0, skipIfZero: true,
                        label: 'CPU Offload (GiB)',
                        tooltip: 'Per-GPU CPU memory to offload model weights to. Lets you run models larger than VRAM at cost of latency.' },
      enableChunkedPrefill: { flag: '--enable-chunked-prefill', type: 'flag', default: false,
                        label: 'Enable Chunked Prefill',
                        tooltip: 'Split long-prompt prefills into chunks so decode can interleave. Reduces decode TBT under heavy prefill load.' },
      // Attention backend
      attentionBackend: { flag: '--attention-backend', type: 'select', default: '',
                        options: ['', 'FLASH_ATTN', 'FLASHINFER', 'XFORMERS', 'TORCH_SDPA', 'TRITON_ATTN_VLLM_V1', 'ROCM_FLASH'],
                        labels: { '': 'auto-pick per arch',
                                  'FLASH_ATTN': 'FlashAttention 2 (sm_80+)',
                                  'FLASHINFER': 'FlashInfer (sm_80+, best for batch decode)',
                                  'XFORMERS': 'xFormers (fallback)',
                                  'TORCH_SDPA': 'PyTorch SDPA (slow fallback)' },
                        label: 'Attention Backend',
                        tooltip: 'Force a specific attention kernel. Leave empty for auto. FLASHINFER best for high-concurrency decode on Ampere+.' },
      // Multimodal
      limitMmImage: { flag: '--limit-mm-per-prompt.image', type: 'number', default: 0, skipIfZero: true,
                        label: 'Max Images/Prompt',
                        tooltip: 'Per-prompt cap on image inputs (vision models). 0 = use model default.' },
      limitMmVideo: { flag: '--limit-mm-per-prompt.video', type: 'number', default: 0, skipIfZero: true,
                        label: 'Max Videos/Prompt',
                        tooltip: 'Per-prompt cap on video inputs. Set 1+ for video-capable models like Qwen2.5-VL.' },
      mmProcessorKwargs: { flag: '--mm-processor-kwargs', type: 'string', default: '',
                        label: 'MM Processor Kwargs (JSON)',
                        tooltip: 'JSON dict passed to the multimodal processor (e.g. {"max_image_size": 768}).' },
      // LoRA
      enableLora:   { flag: '--enable-lora', type: 'flag', default: false,
                        label: 'Enable LoRA',
                        tooltip: 'Enables LoRA adapter hotswapping at request time. Required to use any LoRAs.' },
      maxLoras:     { flag: '--max-loras', type: 'number', default: 1, skipIfZero: true,
                        label: 'Max LoRAs',
                        tooltip: 'Maximum number of LoRAs active simultaneously. Each adds GPU memory.' },
      maxLoraRank:  { flag: '--max-lora-rank', type: 'number', default: 16, skipIfZero: true,
                        label: 'Max LoRA Rank',
                        tooltip: 'Maximum rank (r) any loaded LoRA can have. Set just above what your largest LoRA needs (8/16/32 typical).' },
      loraModules:  { flag: '--lora-modules', type: 'string', default: '',
                        label: 'LoRA Modules',
                        tooltip: 'Comma-separated name=path pairs preloaded at startup (e.g. "math=/loras/math,code=/loras/code"). Reference by name in the "model" field.' },
      // Speculative decoding
      speculativeConfig: { flag: '--speculative-config', type: 'string', default: '',
                        label: 'Speculative Config (JSON)',
                        tooltip: 'JSON config for speculative decoding. E.g. {"model":"<draft>","num_speculative_tokens":4} or {"method":"mtp","num_speculative_tokens":N} for Qwen 3.6 MTP. 1.3-2x throughput when drafts accept.' },
      // Tool calling / Reasoning
      enableAutoToolChoice: { flag: '--enable-auto-tool-choice', type: 'flag', default: false,
                        label: 'Auto Tool Choice',
                        tooltip: 'Lets the model emit tool calls in OpenAI format. Pair with --tool-call-parser.' },
      toolCallParser: { flag: '--tool-call-parser', type: 'select', default: '',
                        options: ['', 'hermes', 'mistral', 'llama3_json', 'pythonic', 'phi4_mini_json', 'granite', 'granite-20b-fc', 'jamba', 'glm45', 'qwen3_xml', 'deepseek_v3', 'kimi_k2', 'minimax_m2', 'qwen3_coder'],
                        labels: { '': 'auto/none' },
                        label: 'Tool Call Parser',
                        tooltip: 'Parser to extract tool calls from model output. Pick to match your model family. "qwen3_xml" for Qwen.' },
      reasoningParser: { flag: '--reasoning-parser', type: 'select', default: '',
                        options: ['', 'deepseek_r1', 'glm45', 'granite', 'qwen3', 'mistral'],
                        labels: { '': 'none' },
                        label: 'Reasoning Parser',
                        tooltip: 'Extracts the model\'s reasoning trace (<think> blocks) into a separate response field. "qwen3" for Qwen 3/3.5/3.6 thinking mode.' },
      // Runner
      runner:       { flag: '--runner', type: 'select', default: '',
                        options: ['', 'generate', 'pooling', 'transcription', 'classify'],
                        labels: { '': 'auto' },
                        label: 'Runner Mode',
                        tooltip: '"generate" = chat/completion; "pooling" = embeddings/rerank; "transcription" = ASR.' },
      // Logging
      disableLogStats: { flag: '--disable-log-stats', type: 'flag', default: false,
                        label: 'Disable Stats Log',
                        tooltip: 'Suppress periodic engine stats logging. Cleaner logs; lose visibility into throughput/queue depth.' },
      maxLogLen:    { flag: '--max-log-len', type: 'number', default: 0, skipIfZero: true,
                        label: 'Max Log Line Length',
                        tooltip: 'Truncate prompt/response strings logged to this many chars. 0 = full.' },
      uvicornLogLevel: { flag: '--uvicorn-log-level', type: 'select', default: 'info',
                        options: ['critical', 'error', 'warning', 'info', 'debug', 'trace'],
                        label: 'Uvicorn Log Level',
                        tooltip: 'HTTP server log verbosity.' },
      // Misc
      revision:     { flag: '--revision', type: 'string', default: '',
                        label: 'HF Revision/Tag',
                        tooltip: 'Specific HuggingFace branch/tag/commit (if loading from hub). Empty = main.' },
      apiKey:       { flag: '--api-key', type: 'string', default: '',
                        label: 'API Key',
                        tooltip: 'If set, clients must send Authorization: Bearer <key>. Useful for public exposure.' },
      seed:         { flag: '--seed', type: 'number', default: 0, skipIfZero: true,
                        label: 'Seed',
                        tooltip: 'Random seed (0 = unset). Set for reproducible generation.' },
      disableCustomAllReduce: { flag: '--disable-custom-all-reduce', type: 'flag', default: false,
                        label: 'Disable Custom All-Reduce',
                        tooltip: 'Fall back to NCCL for TP all-reduce. vLLM\'s custom op is faster but doesn\'t work in PCIe-only multi-GPU.' },
      maxParallelLoadingWorkers: { flag: '--max-parallel-loading-workers', type: 'number', default: 0, skipIfZero: true,
                        label: 'Parallel Loading Workers',
                        tooltip: 'How many shards load in parallel. Default scales with TP; lower if startup OOMs on host RAM.' },
      chatTemplateKwargs: { flag: '--default-chat-template-kwargs', type: 'select', default: '',
                        options: [
                          '',
                          `{"enable_thinking": false}`,
                          `{"enable_thinking": true}`,
                          `{"preserve_thinking": true}`,
                          `{"enable_thinking": false, "preserve_thinking": true}`,
                        ],
                        labels: {
                          '': 'template default',
                          [`{"enable_thinking": false}`]: 'disable thinking (Qwen3.x instruct mode)',
                          [`{"enable_thinking": true}`]: 'force thinking (rarely needed — usually default)',
                          [`{"preserve_thinking": true}`]: 'preserve historical thinking (Qwen3.6 agent loops)',
                          [`{"enable_thinking": false, "preserve_thinking": true}`]: 'Qwen3.6 instruct + preserve history',
                        },
                        label: 'Template Kwargs',
                        tooltip: 'JSON kwargs passed to the Jinja chat template — primary lever for thinking-mode control on Qwen models.\n• Qwen3.6 agent loops: pick "preserve historical thinking" so prior reasoning context carries forward turn-to-turn (improves consistency, often saves tokens)\n• Qwen3.x instruct mode: pick "disable thinking" to skip the <think> block entirely\n• Leave blank to use the model\'s default behavior' },
    },
  };

  // ─── 1Cat-vLLM ────────────────────────────────────────────────────────
  // V100/sm_70-optimized vLLM fork. Same flags as standard vLLM but defaults
  // tuned for the V100 rig (FLASH_ATTN_V100 backend, half precision, fp8 KV,
  // smaller max-num-seqs).
  LAUNCH_TEMPLATES['1cat-vllm'] = {
    ...LAUNCH_TEMPLATES['vllm'],
    command: '/opt/conda/envs/1cat-vllm-sm70/bin/vllm serve',
    args: {
      ...LAUNCH_TEMPLATES['vllm'].args,
      dtype:        { ...LAUNCH_TEMPLATES['vllm'].args.dtype, default: 'half' },
      kvCacheDtype: { ...LAUNCH_TEMPLATES['vllm'].args.kvCacheDtype, default: 'fp8_e5m2' },
      maxNumSeqs:   { ...LAUNCH_TEMPLATES['vllm'].args.maxNumSeqs, default: 4,
                        tooltip: '1Cat-vLLM on V100: keep small (1-8). V100 SMs are limited; high concurrency hurts more than it helps.' },
      gpuMemoryUtilization: { ...LAUNCH_TEMPLATES['vllm'].args.gpuMemoryUtilization, default: 0.85 },
      maxModelLen:  { ...LAUNCH_TEMPLATES['vllm'].args.maxModelLen, default: 131072,
                        tooltip: '1Cat-vLLM defaults to 128K context — V100 32GB has room with fp8 KV cache.' },
    },
    advancedArgs: {
      ...LAUNCH_TEMPLATES['vllm'].advancedArgs,
      attentionBackend: {
        ...LAUNCH_TEMPLATES['vllm'].advancedArgs.attentionBackend,
        default: 'FLASH_ATTN_V100',
        options: [...LAUNCH_TEMPLATES['vllm'].advancedArgs.attentionBackend.options, 'FLASH_ATTN_V100'],
        labels: { ...LAUNCH_TEMPLATES['vllm'].advancedArgs.attentionBackend.labels,
                  'FLASH_ATTN_V100': 'FlashAttention V100 (1Cat-vLLM only, sm_70)' },
        tooltip: '1Cat-vLLM\'s V100-tuned attention kernel. Required for AWQ on V100. Leave on FLASH_ATTN_V100 unless you have a specific reason.' },
      maxNumBatchedTokens: {
        ...LAUNCH_TEMPLATES['vllm'].advancedArgs.maxNumBatchedTokens,
        default: 16384,
        tooltip: '1Cat-vLLM V100 sweet spot: 16384 for AWQ at high context. Reduce if hitting OOM during long-prompt prefill.' },
      // These two exist ONLY here: upstream vLLM 0.18 dropped them with the V1 engine, but this
      // fork predates that and still accepts them. Verified against `vllm serve --help=all` in
      // /opt/conda/envs/1cat-vllm-sm70 — do not "tidy" them back into the shared spec.
      swapSpace: { flag: '--swap-space', type: 'number', default: 0, skipIfZero: true,
                        label: 'CPU Swap Space (GiB)',
                        tooltip: '1Cat-vLLM only. CPU RAM per GPU for KV-cache swap on eviction. 0 = omit the flag.' },
      disableLogRequests: { flag: '--disable-log-requests', type: 'flag', default: false,
                        label: 'Disable Request Log',
                        tooltip: '1Cat-vLLM only. Suppress per-request log lines.' },
    },
  };
