/**
 * providers.js — AI Provider Definitions
 *
 * Static metadata for AI providers (LLM, TTS/STT, image generation) that
 * can be installed into AI agent containers. Each provider has an install
 * script in scripts/providers/{id}.sh that follows the ProxLab install contract.
 *
 * @module providers
 */

export const PROVIDERS = {
  // ─── LLM Providers ──────────────────────────────────────────────────────

  koboldcpp: {
    category: 'llm',
    id: 'koboldcpp',
    name: 'KoboldCpp',
    description: 'GGUF inference server — broad GPU support, easy setup',
    website: 'https://github.com/LostRuins/koboldcpp',
    scriptFile: 'koboldcpp.sh',
    defaultPort: 5001,
    supportedArchs: ['Volta', 'Turing', 'Ampere', 'Ada Lovelace', 'Blackwell'],
    supportedFormats: ['GGUF'],
    complexity: 'easy',
    installChain: ['base-packages', 'drivers/{vendor}', 'gpu-libs/{vendor}', 'providers/koboldcpp'],
  },
  'llama-server': {
    category: 'llm',
    id: 'llama-server',
    name: 'llama.cpp (llama-server)',
    description: 'Upstream llama.cpp server — GGUF, Vulkan backend, inline vision image placement',
    website: 'https://github.com/ggml-org/llama.cpp',
    scriptFile: 'llama-server.sh',
    defaultPort: 8080,
    supportedArchs: ['Volta', 'Turing', 'Ampere', 'Ada Lovelace', 'Blackwell'],
    supportedFormats: ['GGUF'],
    complexity: 'easy',
    installChain: ['base-packages', 'drivers/{vendor}', 'gpu-libs/{vendor}', 'providers/llama-server'],
  },
  ollama: {
    category: 'llm',
    id: 'ollama',
    name: 'Ollama',
    description: 'Simple LLM server — pull and run models with one command',
    website: 'https://ollama.com',
    scriptFile: 'ollama.sh',
    defaultPort: 11434,
    supportedArchs: ['Volta', 'Turing', 'Ampere', 'Ada Lovelace', 'Blackwell'],
    supportedFormats: ['GGUF'],
    complexity: 'easy',
    installChain: ['base-packages', 'drivers/{vendor}', 'gpu-libs/{vendor}', 'providers/ollama'],
  },
  vllm: {
    category: 'llm',
    id: 'vllm',
    name: 'vLLM',
    description: 'High-throughput inference engine — PagedAttention, continuous batching',
    website: 'https://github.com/vllm-project/vllm',
    scriptFile: 'vllm.sh',
    defaultPort: 8000,
    supportedArchs: ['Volta', 'Ampere', 'Ada Lovelace', 'Blackwell'],
    supportedFormats: ['FP16', 'BF16', 'AWQ', 'GPTQ'],
    complexity: 'complex',
    installChain: ['base-packages', 'drivers/{vendor}', 'gpu-libs/{vendor}', 'install-conda', 'providers/prereqs/pytorch-{vendor}', 'providers/vllm'],
  },
  '1cat-vllm': {
    category: 'llm',
    id: '1cat-vllm',
    name: '1Cat-vLLM',
    description: 'V100/SM70-optimized vLLM fork — FLASH_ATTN_V100, AWQ kernels, native MTP, 256K context defaults',
    website: 'https://github.com/1CatAI/1Cat-vLLM',
    scriptFile: '1cat-vllm.sh',
    defaultPort: 8000,
    supportedArchs: ['Volta'],
    supportedFormats: ['FP16', 'BF16', 'AWQ'],
    complexity: 'complex',
    installChain: ['base-packages', 'drivers/{vendor}', 'gpu-libs/{vendor}', 'install-conda', 'providers/1cat-vllm'],
  },
  lmdeploy: {
    category: 'llm',
    id: 'lmdeploy',
    name: 'LMDeploy',
    description: 'TurboMind inference — optimized for large-scale deployment',
    website: 'https://github.com/InternLM/lmdeploy',
    scriptFile: 'lmdeploy.sh',
    defaultPort: 23333,
    supportedArchs: ['Ampere', 'Ada Lovelace', 'Blackwell'],
    supportedFormats: ['FP16', 'BF16', 'AWQ', 'GPTQ'],
    complexity: 'complex',
    installChain: ['base-packages', 'drivers/{vendor}', 'gpu-libs/{vendor}', 'install-conda', 'providers/prereqs/pytorch-{vendor}', 'providers/lmdeploy'],
  },
  sglang: {
    category: 'llm',
    id: 'sglang',
    name: 'SGLang',
    description: 'RadixAttention inference — fast multi-turn, prefix caching',
    website: 'https://github.com/sgl-project/sglang',
    scriptFile: 'sglang.sh',
    defaultPort: 30000,
    supportedArchs: ['Volta', 'Ampere', 'Ada Lovelace', 'Blackwell'],
    supportedFormats: ['FP16', 'BF16', 'AWQ', 'GPTQ'],
    complexity: 'complex',
    installChain: ['base-packages', 'drivers/{vendor}', 'gpu-libs/{vendor}', 'install-conda', 'providers/prereqs/pytorch-{vendor}', 'providers/sglang'],
  },
  tabbyapi: {
    category: 'llm',
    id: 'tabbyapi',
    name: 'TabbyAPI',
    description: 'ExLlama API server — EXL2/EXL3 quants, best quality-per-bit',
    website: 'https://github.com/theroyallab/tabbyAPI',
    scriptFile: 'tabbyapi.sh',
    defaultPort: 5000,
    supportedArchs: ['Volta', 'Ampere', 'Ada Lovelace', 'Blackwell'],
    supportedFormats: ['EXL2', 'EXL3', 'GPTQ'],
    complexity: 'complex',
    installChain: ['base-packages', 'drivers/{vendor}', 'gpu-libs/{vendor}', 'install-conda', 'providers/prereqs/pytorch-{vendor}', 'providers/tabbyapi'],
  },
  aphrodite: {
    category: 'llm',
    id: 'aphrodite',
    name: 'Aphrodite',
    description: 'vLLM fork — EXL2 + GGUF + advanced samplers (DRY, XTC, Mirostat)',
    website: 'https://github.com/aphrodite-engine/aphrodite-engine',
    scriptFile: 'aphrodite.sh',
    defaultPort: 2242,
    supportedArchs: ['Volta', 'Ampere', 'Ada Lovelace', 'Blackwell'],
    supportedFormats: ['FP16', 'BF16', 'AWQ', 'GPTQ', 'EXL2'],
    complexity: 'complex',
    installChain: ['base-packages', 'drivers/{vendor}', 'gpu-libs/{vendor}', 'install-conda', 'providers/prereqs/pytorch-{vendor}', 'providers/aphrodite'],
  },

  // ─── TTS / STT Providers ────────────────────────────────────────────────

  alltalk: {
    category: 'tts',
    id: 'alltalk',
    name: 'AllTalk TTS',
    description: 'Coqui-based TTS — voice cloning, finetuning, SillyTavern integration',
    website: 'https://github.com/erew123/alltalk_tts',
    scriptFile: 'alltalk.sh',
    defaultPort: 7851,
    supportedArchs: ['Volta', 'Turing', 'Ampere', 'Ada Lovelace', 'Blackwell'],
    supportedFormats: [],
    complexity: 'complex',
    installChain: ['base-packages', 'drivers/{vendor}', 'gpu-libs/{vendor}', 'install-conda', 'providers/prereqs/pytorch-{vendor}', 'providers/alltalk'],
    installExtras: [
      { id: 'rvc', label: 'RVC Voice Conversion', pip: 'faiss-cpu', size: '~120MB' },
      { id: 'deepspeed', label: 'DeepSpeed', pip: 'deepspeed', size: '~200MB' },
    ],
    installModels: [
      { id: 'xtts-v2', label: 'XTTS v2', hfRepo: 'coqui/XTTS-v2', size: '~1.8GB' },
    ],
  },
  f5tts: {
    category: 'tts',
    id: 'f5tts',
    name: 'F5-TTS',
    description: 'Zero-shot voice cloning — flow matching, fast inference, multilingual',
    website: 'https://github.com/SWivid/F5-TTS',
    scriptFile: 'f5tts.sh',
    defaultPort: 7860,
    supportedArchs: ['Volta', 'Turing', 'Ampere', 'Ada Lovelace', 'Blackwell'],
    supportedFormats: [],
    complexity: 'complex',
    installChain: ['base-packages', 'drivers/{vendor}', 'gpu-libs/{vendor}', 'install-conda', 'providers/prereqs/pytorch-{vendor}', 'providers/f5tts'],
  },
  dramabox: {
    category: 'tts',
    id: 'dramabox',
    name: 'Dramabox',
    description: 'Theatrical diffusion TTS — IC-LoRA on LTX-2.3 audio DiT with Gemma 3 12B text encoder. Stage-direction syntax for emotion control.',
    website: 'https://github.com/resemble-ai/DramaBox',
    scriptFile: 'dramabox.sh',
    defaultPort: 8885,
    supportedArchs: ['Volta', 'Turing', 'Ampere', 'Ada Lovelace', 'Blackwell'],
    supportedFormats: [],
    complexity: 'complex',
    installChain: ['base-packages', 'drivers/{vendor}', 'gpu-libs/{vendor}', 'install-conda', 'providers/prereqs/pytorch-{vendor}', 'providers/dramabox'],
  },
  'proxlab-tts': {
    category: 'tts',
    id: 'proxlab-tts',
    name: 'AI-Lab TTS',
    description: 'OpenAI-compatible TTS — Chatterbox-Turbo voice cloning, drop-in for SillyTavern & HA',
    website: 'https://github.com/resemble-ai/chatterbox',
    scriptFile: 'proxlab-tts.sh',
    defaultPort: 8880,
    supportedArchs: ['Volta', 'Turing', 'Ampere', 'Ada Lovelace', 'Blackwell'],
    supportedFormats: [],
    complexity: 'easy',
    installChain: ['base-packages', 'drivers/{vendor}', 'gpu-libs/{vendor}', 'install-conda',
                   'providers/prereqs/pytorch-{vendor}', 'providers/proxlab-tts'],
  },
  rvc: {
    category: 'tts',
    id: 'rvc',
    name: 'RVC Voice Conversion',
    description: 'Retrieval-based voice conversion — re-voices TTS output through a trained speaker model',
    website: 'https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI',
    scriptFile: 'rvc.sh',
    defaultPort: 7100,
    supportedArchs: ['Volta', 'Turing', 'Ampere', 'Ada Lovelace', 'Blackwell'],
    supportedFormats: [],
    complexity: 'medium',
    installChain: ['base-packages', 'drivers/{vendor}', 'gpu-libs/{vendor}', 'install-conda',
                   'providers/prereqs/pytorch-{vendor}', 'providers/rvc'],
  },
  'qwen-tts': {
    category: 'tts',
    id: 'qwen-tts',
    name: 'Qwen3-TTS',
    description: 'OpenAI-compatible TTS — Qwen3-TTS (10 languages, 3-sec voice cloning, ~97 ms streaming latency)',
    website: 'https://github.com/QwenLM/Qwen3-TTS',
    scriptFile: 'qwen-tts.sh',
    defaultPort: 8881,
    supportedArchs: ['Volta', 'Turing', 'Ampere', 'Ada Lovelace', 'Blackwell'],
    supportedFormats: [],
    complexity: 'easy',
    installChain: ['base-packages', 'drivers/{vendor}', 'gpu-libs/{vendor}', 'install-conda',
                   'providers/prereqs/pytorch-{vendor}', 'providers/qwen-tts'],
  },
  's2-pro': {
    category: 'tts',
    id: 's2-pro',
    name: 'Fish-Audio S2-Pro',
    description: 'OpenAI-compatible TTS — Fish-Audio S2-Pro (5B, 80+ languages, 15K+ inline tags [whisper] [excited] etc, zero-shot voice cloning). License: Fish Audio Research (non-commercial).',
    website: 'https://huggingface.co/fishaudio/s2-pro',
    scriptFile: 's2-pro.sh',
    defaultPort: 8882,
    // S2-Pro is 5B params BF16 (~10 GB VRAM) and SGLang-Omni leans on
    // recent flash-attn + paged KV — Volta/Turing are likely to choke
    // on the kernel requirements. Restrict to Ampere+ to set
    // expectations correctly.
    supportedArchs: ['Ampere', 'Ada Lovelace', 'Blackwell'],
    supportedFormats: [],
    complexity: 'medium',
    installChain: ['base-packages', 'drivers/{vendor}', 'gpu-libs/{vendor}', 'install-conda',
                   'providers/prereqs/pytorch-{vendor}', 'providers/s2-pro'],
  },
  kokoro: {
    category: 'tts',
    id: 'kokoro',
    name: 'Kokoro TTS',
    description: 'Lightweight 82M model — OpenAI-compatible API, fast and efficient',
    website: 'https://github.com/remsky/Kokoro-FastAPI',
    scriptFile: 'kokoro.sh',
    defaultPort: 8880,
    supportedArchs: ['Volta', 'Turing', 'Ampere', 'Ada Lovelace', 'Blackwell'],
    supportedFormats: [],
    complexity: 'easy',
    installChain: ['base-packages', 'drivers/{vendor}', 'gpu-libs/{vendor}', 'install-conda', 'providers/prereqs/pytorch-{vendor}', 'providers/kokoro'],
  },
  'openedai-speech': {
    category: 'tts',
    id: 'openedai-speech',
    name: 'OpenedAI Speech',
    description: 'OpenAI-compatible TTS API — wraps XTTS, Piper, and other backends',
    website: 'https://github.com/matatonic/openedai-speech',
    scriptFile: 'openedai-speech.sh',
    defaultPort: 8000,
    supportedArchs: ['Volta', 'Turing', 'Ampere', 'Ada Lovelace', 'Blackwell'],
    supportedFormats: [],
    complexity: 'complex',
    installChain: ['base-packages', 'drivers/{vendor}', 'gpu-libs/{vendor}', 'install-conda', 'providers/prereqs/pytorch-{vendor}', 'providers/openedai-speech'],
  },
  'tts-webui': {
    category: 'tts',
    id: 'tts-webui',
    name: 'TTS-WebUI',
    description: 'Multi-model TTS hub — 15+ backends including Piper, XTTS, F5, Kokoro',
    website: 'https://github.com/rsxdalv/TTS-WebUI',
    scriptFile: 'tts-webui.sh',
    defaultPort: 7770,
    supportedArchs: ['Volta', 'Turing', 'Ampere', 'Ada Lovelace', 'Blackwell'],
    supportedFormats: [],
    complexity: 'complex',
    installChain: ['base-packages', 'drivers/{vendor}', 'gpu-libs/{vendor}', 'install-conda', 'providers/prereqs/pytorch-{vendor}', 'providers/tts-webui'],
  },
  piper: {
    category: 'tts',
    id: 'piper',
    name: 'Piper TTS',
    description: 'Lightweight VITS TTS — CPU-fast, Home Assistant ready, 20ms latency',
    website: 'https://github.com/rhasspy/piper',
    scriptFile: 'piper.sh',
    defaultPort: 5000,
    supportedArchs: ['Volta', 'Turing', 'Ampere', 'Ada Lovelace', 'Blackwell'],
    supportedFormats: [],
    complexity: 'easy',
    installChain: ['base-packages', 'install-conda', 'providers/piper'],
  },
  'faster-whisper': {
    category: 'tts',
    id: 'faster-whisper',
    name: 'Faster-Whisper STT',
    description: 'CTranslate2 Whisper — 4x faster transcription, OpenAI-compatible API',
    website: 'https://github.com/SYSTRAN/faster-whisper',
    scriptFile: 'faster-whisper.sh',
    defaultPort: 8079,
    supportedArchs: ['Volta', 'Turing', 'Ampere', 'Ada Lovelace', 'Blackwell'],
    supportedFormats: [],
    complexity: 'easy',
    installChain: ['base-packages', 'install-conda', 'providers/faster-whisper'],
  },

  // ─── Image Generation Providers ────────────────────────────────────────

  comfyui: {
    category: 'image',
    id: 'comfyui',
    name: 'ComfyUI',
    description: 'Node-based workflow UI — modular, extensible, custom node ecosystem',
    website: 'https://github.com/comfyanonymous/ComfyUI',
    scriptFile: 'comfyui.sh',
    defaultPort: 8188,
    supportedArchs: ['Volta', 'Turing', 'Ampere', 'Ada Lovelace', 'Blackwell'],
    supportedFormats: [],
    complexity: 'complex',
    installChain: ['base-packages', 'drivers/{vendor}', 'gpu-libs/{vendor}', 'install-conda', 'providers/prereqs/pytorch-{vendor}', 'providers/comfyui'],
    installExtras: [
      { id: 'manager', label: 'ComfyUI Manager', size: '~50MB' },
    ],
  },
  sdnext: {
    category: 'image',
    id: 'sdnext',
    name: 'SD.Next',
    description: 'Vladmandic A1111 successor — SD/SDXL/SD3/Flux, built-in installer',
    website: 'https://github.com/vladmandic/automatic',
    scriptFile: 'sdnext.sh',
    defaultPort: 7860,
    supportedArchs: ['Volta', 'Turing', 'Ampere', 'Ada Lovelace', 'Blackwell'],
    supportedFormats: [],
    complexity: 'complex',
    installChain: ['base-packages', 'drivers/{vendor}', 'gpu-libs/{vendor}', 'install-conda', 'providers/prereqs/pytorch-{vendor}', 'providers/sdnext'],
  },
  fooocus: {
    category: 'image',
    id: 'fooocus',
    name: 'Fooocus',
    description: 'Simplified Midjourney-like UI — minimal config, SDXL focus',
    website: 'https://github.com/lllyasviel/Fooocus',
    scriptFile: 'fooocus.sh',
    defaultPort: 7865,
    supportedArchs: ['Turing', 'Ampere', 'Ada Lovelace', 'Blackwell'],
    supportedFormats: [],
    complexity: 'easy',
    installChain: ['base-packages', 'drivers/{vendor}', 'gpu-libs/{vendor}', 'install-conda', 'providers/prereqs/pytorch-{vendor}', 'providers/fooocus'],
  },
  invokeai: {
    category: 'image',
    id: 'invokeai',
    name: 'InvokeAI',
    description: 'Professional UI with canvas — inpainting, outpainting, control layers',
    website: 'https://github.com/invoke-ai/InvokeAI',
    scriptFile: 'invokeai.sh',
    defaultPort: 9090,
    supportedArchs: ['Turing', 'Ampere', 'Ada Lovelace', 'Blackwell'],
    supportedFormats: [],
    complexity: 'complex',
    installChain: ['base-packages', 'drivers/{vendor}', 'gpu-libs/{vendor}', 'install-conda', 'providers/prereqs/pytorch-{vendor}', 'providers/invokeai'],
  },
  fluxgym: {
    category: 'training',
    id: 'fluxgym',
    name: 'FluxGym',
    description: 'Flux LoRA training UI — kohya backend, simple workflow, low VRAM',
    website: 'https://github.com/cocktailpeanut/fluxgym',
    scriptFile: 'fluxgym.sh',
    defaultPort: 7860,
    supportedArchs: ['Ampere', 'Ada Lovelace', 'Blackwell'],
    supportedFormats: [],
    complexity: 'complex',
    installChain: ['base-packages', 'drivers/{vendor}', 'gpu-libs/{vendor}', 'install-conda', 'providers/prereqs/pytorch-{vendor}', 'providers/fluxgym'],
  },

  // ─── LoRA Training Providers ───────────────────────────────────────────

  'kohya-ss': {
    category: 'training',
    id: 'kohya-ss',
    name: 'kohya_ss (sd-scripts)',
    description: 'Most popular LoRA trainer — SD1.5/SDXL/SD3/Flux, full GUI',
    website: 'https://github.com/bmaltais/kohya_ss',
    scriptFile: 'kohya-ss.sh',
    defaultPort: 7860,
    supportedArchs: ['Ampere', 'Ada Lovelace', 'Blackwell'],
    supportedFormats: [],
    complexity: 'complex',
    installChain: ['base-packages', 'drivers/{vendor}', 'gpu-libs/{vendor}', 'install-conda', 'providers/prereqs/pytorch-{vendor}', 'providers/kohya-ss'],
  },
  simpletuner: {
    category: 'training',
    id: 'simpletuner',
    name: 'SimpleTuner',
    description: 'Modern trainer — 20+ model support, Flux/SDXL/SD3, pip installable',
    website: 'https://github.com/bghira/SimpleTuner',
    scriptFile: 'simpletuner.sh',
    defaultPort: null,
    supportedArchs: ['Ampere', 'Ada Lovelace', 'Blackwell'],
    supportedFormats: [],
    complexity: 'complex',
    installChain: ['base-packages', 'drivers/{vendor}', 'gpu-libs/{vendor}', 'install-conda', 'providers/prereqs/pytorch-{vendor}', 'providers/simpletuner'],
  },
  onetrainer: {
    category: 'training',
    id: 'onetrainer',
    name: 'OneTrainer',
    description: 'GUI trainer — SD1.5-3.5/SDXL/Flux/PixArt/Cascade, all-in-one',
    website: 'https://github.com/Nerogar/OneTrainer',
    scriptFile: 'onetrainer.sh',
    defaultPort: null,
    supportedArchs: ['Ampere', 'Ada Lovelace', 'Blackwell'],
    supportedFormats: [],
    complexity: 'complex',
    installChain: ['base-packages', 'drivers/{vendor}', 'gpu-libs/{vendor}', 'install-conda', 'providers/prereqs/pytorch-{vendor}', 'providers/onetrainer'],
  },
  'ai-toolkit': {
    category: 'training',
    id: 'ai-toolkit',
    name: 'AI Toolkit (Ostris)',
    description: 'Lightweight trainer — Flux/SDXL focus, simple config, fast iteration',
    website: 'https://github.com/ostris/ai-toolkit',
    scriptFile: 'ai-toolkit.sh',
    defaultPort: null,
    supportedArchs: ['Ampere', 'Ada Lovelace', 'Blackwell'],
    supportedFormats: [],
    complexity: 'complex',
    installChain: ['base-packages', 'drivers/{vendor}', 'gpu-libs/{vendor}', 'install-conda', 'providers/prereqs/pytorch-{vendor}', 'providers/ai-toolkit'],
  },

  // ─── Tools Providers ──────────────────────────────────────────────────

  'audio-tools': {
    category: 'tools',
    id: 'audio-tools',
    name: 'Audio Tools',
    description: 'Voice isolation (Demucs), denoising (Resemble Enhance), upscaling (FLowHigh)',
    website: 'https://github.com/facebookresearch/demucs',
    scriptFile: null,
    defaultPort: 8890,
    supportedArchs: ['Volta', 'Turing', 'Ampere', 'Ada Lovelace', 'Blackwell'],
    supportedFormats: [],
    complexity: 'medium',
    installChain: [],
  },
};

/**
 * Get a single provider by ID.
 * @param {string} id - Provider ID (e.g. 'koboldcpp')
 * @returns {Object|null} Provider definition or null
 */
export function getProvider(id) {
  return PROVIDERS[id] || null;
}

/**
 * Get all provider definitions as an array.
 * @returns {Array<Object>} All providers
 */
export function getAllProviders() {
  return Object.values(PROVIDERS);
}
