#!/bin/bash
# ProxLab Provider Installer: Faster-Whisper STT
# Usage: ./faster-whisper.sh [install|uninstall|status]
#
# faster-whisper is a CTranslate2-based Whisper implementation providing
# up to 4x faster transcription. Includes a minimal OpenAI-compatible
# /v1/audio/transcriptions API server.
#
# Environment variables (set by ProxLab installer service):
#   PROXLAB_INSTALL_DIR - Install directory (default: /opt/faster-whisper)
#   PROXLAB_CONDA_ENV   - Conda env name (default: faster-whisper)

set -euo pipefail

ACTION="${1:-install}"
INSTALL_DIR="${PROXLAB_INSTALL_DIR:-/opt/faster-whisper}"
CONDA_ENV="${PROXLAB_CONDA_ENV:-faster-whisper}"

# Models to pre-download: name → HuggingFace repo
declare -A DEFAULT_MODELS=(
    ["small"]="Systran/faster-whisper-small"
    ["large-v3-turbo"]="mobiuslabsgmbh/faster-whisper-large-v3-turbo"
)

# Ensure conda is on PATH
export PATH="/opt/conda/bin:$PATH"

# ─── Actions ─────────────────────────────────────────────────────────────

do_install() {
    if [ -f "$INSTALL_DIR/.version" ]; then
        EXISTING_VER=$(cat "$INSTALL_DIR/.version")
        if conda run -n "$CONDA_ENV" python3 -c "import faster_whisper" 2>/dev/null; then
            echo "Faster-Whisper already installed: $EXISTING_VER"
            echo "PROXLAB_STATUS=installed"
            echo "PROXLAB_VERSION=$EXISTING_VER"
            return 0
        fi
        echo "Faster-Whisper version file exists but module missing — reinstalling"
    fi

    if ! command -v conda &>/dev/null; then
        echo "ERROR: conda not found — install-conda.sh must run first"
        echo "PROXLAB_STATUS=error"
        exit 1
    fi

    # Create conda env if it doesn't exist (lightweight providers skip pytorch prereq)
    PYTHON_VER="${PROXLAB_PYTHON_VERSION:-3.12}"
    if [ "$CONDA_ENV" != "base" ]; then
        if ! conda env list 2>/dev/null | grep -qw "^${CONDA_ENV} "; then
            echo "Creating conda environment: $CONDA_ENV (Python ${PYTHON_VER})..."
            conda create -n "$CONDA_ENV" python="$PYTHON_VER" -y 2>&1
        else
            echo "Conda environment '$CONDA_ENV' already exists"
        fi
    fi

    echo "Installing Faster-Whisper STT..."

    # Core library + API server deps
    conda run -n "$CONDA_ENV" pip install \
        faster-whisper \
        fastapi \
        uvicorn \
        python-multipart \
        2>&1

    # CUDA runtime libs for CTranslate2. NOT optional on a GPU box, and their absence
    # produces the nastiest possible failure mode: the service starts clean and fast,
    # /v1/models answers, and then EVERY transcription 500s with
    #   RuntimeError: Library libcublas.so.12 is not found or cannot be loaded
    # because CTranslate2 links cuBLAS/cuDNN lazily at the first encode() rather than at
    # model load. faster-whisper does not pull these in itself (it has no torch dep, which
    # is also why the usual sm_70 torch/CUDA pinning does not apply here).
    echo "Installing CUDA runtime libraries for CTranslate2 (cuBLAS 12 + cuDNN 9)..."
    conda run -n "$CONDA_ENV" pip install \
        nvidia-cublas-cu12 \
        nvidia-cudnn-cu12 \
        2>&1

    # Register them with the SYSTEM loader rather than relying on LD_LIBRARY_PATH in the
    # launch script: that script is regenerated by AI-Lab on every relaunch, so anything
    # written into it is reverted silently the next time the service is started.
    NV_LIB_DIRS=$(ls -d "$(conda run -n "$CONDA_ENV" python -c 'import site;print(site.getsitepackages()[0])' 2>/dev/null)"/nvidia/*/lib 2>/dev/null)
    if [ -n "$NV_LIB_DIRS" ]; then
        echo "$NV_LIB_DIRS" > /etc/ld.so.conf.d/faster-whisper-cuda.conf
        ldconfig
        if ldconfig -p | grep -q "libcublas.so.12"; then
            echo "libcublas.so.12 resolvable by the system loader: OK"
        else
            echo "WARNING: libcublas.so.12 still not resolvable — GPU transcription will fail at first use"
        fi
    else
        echo "WARNING: could not locate the installed nvidia lib dirs — GPU transcription may fail at first use"
    fi

    # Create install dir
    mkdir -p "$INSTALL_DIR"

    # Write the OpenAI-compatible API server
    cat > "$INSTALL_DIR/server.py" << 'SERVER_EOF'
"""
Faster-Whisper STT Server — OpenAI-compatible /v1/audio/transcriptions API.
Usage: python server.py [--model small] [--host 0.0.0.0] [--port 8000] [--device auto]
"""
import argparse
import io
import time

import uvicorn
from fastapi import FastAPI, File, Form, UploadFile
from faster_whisper import WhisperModel

app = FastAPI(title="Faster-Whisper STT")
model: WhisperModel = None
model_name: str = "small"


def load_model(name: str, device: str = "auto", compute_type: str = "auto"):
    global model, model_name
    print(f"Loading model: {name} (device={device}, compute_type={compute_type})", flush=True)
    print("Downloading model if not cached (this may take a moment)...", flush=True)
    model = WhisperModel(name, device=device, compute_type=compute_type)
    model_name = name
    print(f"Model {name} loaded and ready", flush=True)


@app.post("/v1/audio/transcriptions")
async def transcribe(
    file: UploadFile = File(...),
    model: str = Form("whisper-1"),
    language: str = Form(None),
    response_format: str = Form("json"),
    temperature: float = Form(0.0),
):
    audio_bytes = await file.read()
    segments, info = globals()["model"].transcribe(
        io.BytesIO(audio_bytes),
        language=language if language else None,
        temperature=temperature,
        vad_filter=True,
    )
    text = "".join(seg.text for seg in segments).strip()

    if response_format == "text":
        from fastapi.responses import PlainTextResponse
        return PlainTextResponse(text)
    elif response_format == "verbose_json":
        return {
            "text": text,
            "language": info.language,
            "duration": info.duration,
        }
    return {"text": text}


@app.post("/v1/audio/translations")
async def translate(
    file: UploadFile = File(...),
    model: str = Form("whisper-1"),
    response_format: str = Form("json"),
):
    audio_bytes = await file.read()
    segments, info = globals()["model"].transcribe(
        io.BytesIO(audio_bytes),
        task="translate",
        vad_filter=True,
    )
    text = "".join(seg.text for seg in segments).strip()

    if response_format == "text":
        from fastapi.responses import PlainTextResponse
        return PlainTextResponse(text)
    return {"text": text}


@app.get("/v1/models")
async def list_models():
    return {"data": [{"id": model_name, "object": "model"}]}


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Faster-Whisper STT Server")
    parser.add_argument("--model", "-m", default="small", help="Model name or path")
    parser.add_argument("--host", "-H", default="0.0.0.0", help="Listen host")
    parser.add_argument("--port", "-p", type=int, default=8000, help="Listen port")
    parser.add_argument("--device", "-d", default="auto", help="Device: auto, cuda, cpu")
    parser.add_argument("--compute-type", "-c", default="auto", help="Compute type: auto, int8, float16, float32")
    args = parser.parse_args()

    load_model(args.model, args.device, args.compute_type)
    uvicorn.run(app, host=args.host, port=args.port)
SERVER_EOF

    # Pre-download models (with progress logging)
    echo "Pre-downloading models..."
    for name in "${!DEFAULT_MODELS[@]}"; do
        repo="${DEFAULT_MODELS[$name]}"
        echo "  Downloading: $name ($repo) ..."
        conda run -n "$CONDA_ENV" python3 -c "
import sys, os
os.environ['HF_HUB_ENABLE_HF_TRANSFER'] = '0'
from huggingface_hub import snapshot_download
from huggingface_hub.utils import tqdm as hf_tqdm

# Enable tqdm progress bars to stdout
snapshot_download('$repo', local_files_only=False)
print('  OK: $name downloaded', flush=True)
" 2>&1 || echo "  WARNING: Failed to download $name (non-fatal)"
    done

    # Get version
    VER=$(conda run -n "$CONDA_ENV" python3 -c "import faster_whisper; print(faster_whisper.__version__)" 2>/dev/null || echo "unknown")
    echo "$VER" > "$INSTALL_DIR/.version"

    # Create convenience launcher
    cat > "$INSTALL_DIR/serve.sh" << SERVE_EOF
#!/bin/bash
# Faster-Whisper STT server — usage: ./serve.sh [--model small] [--port 8000]
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:\$LD_LIBRARY_PATH
exec /opt/conda/envs/$CONDA_ENV/bin/python3 "$INSTALL_DIR/server.py" \\
    --host 0.0.0.0 "\$@"
SERVE_EOF
    chmod +x "$INSTALL_DIR/serve.sh"

    echo "Faster-Whisper ${VER} installed to $INSTALL_DIR"
    echo "PROXLAB_STATUS=installed"
    echo "PROXLAB_VERSION=$VER"
}

do_uninstall() {
    if command -v conda &>/dev/null && [ "$CONDA_ENV" != "base" ]; then
        echo "Removing conda environment: $CONDA_ENV"
        conda env remove -n "$CONDA_ENV" -y 2>/dev/null || true
    fi

    if [ -d "$INSTALL_DIR" ]; then
        rm -rf "$INSTALL_DIR"
        echo "Removed $INSTALL_DIR"
    fi
    echo "PROXLAB_STATUS=not_installed"
}

do_status() {
    if [ -f "$INSTALL_DIR/.version" ]; then
        VER=$(cat "$INSTALL_DIR/.version")
        if conda run -n "$CONDA_ENV" python3 -c "import faster_whisper" 2>/dev/null; then
            echo "PROXLAB_STATUS=installed"
            echo "PROXLAB_VERSION=$VER"
        else
            echo "PROXLAB_STATUS=not_installed"
        fi
    else
        echo "PROXLAB_STATUS=not_installed"
    fi
}

# ─── Dispatch ────────────────────────────────────────────────────────────

case "$ACTION" in
    install)   do_install   ;;
    uninstall) do_uninstall ;;
    status)    do_status    ;;
    *)
        echo "Usage: $0 {install|uninstall|status}"
        exit 1
        ;;
esac
